name: flutter_bottom_sheet_pickers_example
description: Example app for flutter_bottom_sheet_pickers.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bottom_sheet_pickers:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
