name: flutter_bottom_sheet_pickers
description: Customizable Flutter bottom sheet pickers for single, multiple, searchable, lazy loaded, and cascade selection.
homepage: https://github.com/leo1394/flutter_bottom_sheet_pickers
repository: https://github.com/leo1394/flutter_bottom_sheet_pickers
issue_tracker: https://github.com/leo1394/flutter_bottom_sheet_pickers/issues
version: 0.1.0

topics:
  - picker
  - bottom-sheet
  - cascade-picker
  - flutter-picker
  - selection

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
